name: 0 - Run Everything


on:
  workflow_dispatch:
  push:
    branches:
      - 'releases/v*'
    tags:
      - 'v*.*.*'

  pull_request:
    branches:
      - 'releases/v*'


jobs:
  tests:
    uses: ./.github/workflows/ci.yaml
  packaging:
    needs: tests
    uses: ./.github/workflows/packaging.yaml
