name: 1 - package to pypi 

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "master"

jobs:

  run-tests:
    
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: checkout 
        uses: action/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        # Step specific environment variables
        run: |
          tox

